# docker/nginx/default.conf

# -------------------------------
# NGINX Server Configuration
# -------------------------------

# -------------------------------
# Define multiple backend servers
# -------------------------------
upstream backend {
    # least_conn; # better distribution than default avoids sticky behavior
    # resolver 127.0.0.11 valid=10s; # Forces NGINX to re-resolve Docker DNS every 10 seconds (useful for dynamic scaling)
    server app:3000;  # Docker auto load balances across replicas
}

server {
    # Listen on port 80 (HTTP)
    listen 80;

    # Server name (can be domain later)
    server_name localhost;

    # -------------------------------
    # Reverse Proxy Configuration
    # -------------------------------
    location / {
        # Forward request to Node.js app container
        # proxy_pass http://app:3000; # 'app' is the service name defined in docker-compose.yml

        proxy_pass http://backend; # Use upstream for better load balancing (future use)

        # Preserve original request information
        proxy_http_version 1.1;

        # Upgrade headers (important for websockets, future use)
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';

        # Forward original host
        proxy_set_header Host $host;

        # Forward client IP (important for logging & rate limiting)
        proxy_set_header X-Real-IP $remote_addr;

        # Prevent caching issues
        proxy_cache_bypass $http_upgrade;
    }
}